### ISSUE TITLE
Add Telescope Movement Commands

### ISSUE THREAD

**Issue by ddefrancesco** [ddefrancesco/scoperunner_server#20]
Add a route to implement scope movement commands.

api path : /slew
method: POST
transcoding commands: :Mxx#

- [x] Move in a direction (nsew)
- [ ] Move in a direction (nsew) for specified time (millisecs)
- [ ] #27
- [x] Slew to target Alt and Az
