### ISSUE TITLE
Scope Initialization sequence

### ISSUE THREAD

**Issue by ddefrancesco** [ddefrancesco/scoperunner_server#21]
Compose Autostar commands to do telescope initialization process :
Initialize

- [x] Set Date
- [x] Set Local Time
- [x] Set Current Place (lat/long) --> Automatic conversion of GPS Coordinates took from Api
- [ ] Set UTC Offset --> Seems to be ineffective on etx105 (firmware 26e)
