### ISSUE TITLE
Epic #1: Add Get Telescope Info API

### ISSUE THREAD

**Issue by ddefrancesco** [ddefrancesco/scoperunner_server#4]
Add a route to implement scope settings info.

api path : /info
method: GET
transcoding commands: :Gxx#

- [X] Altitude *:GA#*
- [X] Local Telescope Time (12h) *:Ga#*
- [X] Browse Brighter Magnitude limit *:Gb#*
- [X] Current Date *:GC#*
- [X] Clock Format (12/24) *:Gc#*
- [X] Telescope Declination *:GD#*
- [X] Currently selected target Declination *:Gd#*
- [X] Find field diameter *:GF#*
- [X] Browse Fainter Magnitude limit *:Gf#*
- [X] UTC offset time *:GG#*
- [X] Current site Longitude *:Gg#*
- [X] High Limit *:Gh#*
- [X] Local Time (24h) *:GL#*
- [X] Larger size limit *:GI#*
- [X] Lower limit *:Go#*
- [X] Minimum quality for FIND Operation *:Gq#*
- [X] Telescope RA *:GR#*
- [X] Current target/object RA *:Gr#*
- [X] Sidereal Time *:GS#*
- [X] Smaller size limit *:Gs#*
- [X] Tracking rate *:GT#*
- [X] Current Site Latitude *:Gt#*
- [X] Telescope Firmware Date *:GVD#*
- [X] Telescope Firmware Number *:GVN#* 
- [X] Telescope Product Name *:GVP#*
- [X] Telescope Firmware Time *:GVT#*
- [X] Deepsky object search string *:Gy#*
- [X] Telescope Azimuth *:GZ#*

**Comment by ddefrancesco** [comment]
### **[enhancement]** Multiparameter Info API

**Request**
/info/items=altitude,current_date,local_time_24h

**Response**
[
  {"code":200,"response":"12:02:16#","cmd":":Ga#"},
  {"code":200,"response":"01/15/24#","cmd":":GC#"},
  {"code":200,"response":"s12:03:59#","cmd":":GL#"}
]
